@HOST = http://localhost:8080/api

PATCH  {{HOST}}/budget-account/update-total-budget/2024/3.1.1.4.09.3 DESPESA CONTROLADORIA/1.2.2.2.01.1.00262-3 INSTALAÇÕES/marco HTTP/1.1
Content-Type: application/json

{
    "totalValue": 10,
    "canceled": true
}