version: "3.8"

services:
  nest-api:
    container_name: scontrol-api
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/home/node/app
    working_dir: /home/node/app
    ports:
      - 8080:8080
    networks:
      - scontrol
    tty: true
    depends_on:
      - pg-db-dev
      - pg-db-test
      # - redis

  pg-db-dev:
    image: postgres:14
    container_name: scontrol-db-dev
    environment:
      POSTGRES_PASSWORD: growdev2023
      POSTGRES_USER: growdev
      POSTGRES_DB: scontrol
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - scontrol_postgres:/var/lib/postgresql/data
    networks:
      - scontrol

  pg-db-test:
    image: postgres:14
    container_name: scontrol-db-test
    deploy:
      resources:
        limits:
          memory: 512M
    environment:
      POSTGRES_PASSWORD: test2022
      POSTGRES_USER: test
      POSTGRES_DB: test_app
    ports:
      - 5433:5432
    networks:
      - scontrol

  # redis:
  #   image: redis
  #   container_name: scontrol-redis
  #   command: redis-server --requirepass growdev2023
  #   ports:
  #     - 6379:6379
  #   networks:
  #     - scontrol

networks:
  scontrol:
    driver: bridge

volumes:
  scontrol_postgres:
