version: '3.8'

services:
  nest-api:
    container_name: scontrol-api-hmg
    image: ssystem-api-hmg
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - 8081:8080
    env_file:
      - .env.prod # configurar env de produção
    networks:
      - ssystem_hmg
    depends_on:
      - database-hmg

  database-hmg:
    image: postgres:14
    container_name: database-hmg
    environment:
      POSTGRES_PASSWORD: growdev2023
      POSTGRES_USER: growdev
      POSTGRES_DB: scontrol
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5433:5432
    volumes:
      - postgres_hmg:/var/lib/postgresql/data
    networks:
      - ssystem_hmg

networks:
  ssystem_hmg:
    driver: bridge

volumes:
  postgres_hmg:
