@HOST = http://localhost:8080/api

PUT {{HOST}}/payment-request-general/9fef5be8-e163-45d2-b46a-901a25f679d6/9cf72d2a-428a-4b3f-aff2-58dd75e11204 HTTP/1.1
Content-Type: application/json

{
  "description": "algo",
  "supplier": "33683111000280",
  "requiredReceipt": true,
  "totalValue": 50,
  "accountingAccount": "3.1.2.1.01.3.00850-8 RESULTADO VARIACOES CAMBIAIS",
  "CardHolder": null,
  "paymentSchedules": [
    {
      "uid": "afdda861-4279-4c80-b29e-e72379a36a54",
      "value": 45,
      "dueDate": "2024-04-21T03:00:00.000Z"
    }
  ], 
  "files": [
    {
      "uid": "7149b04c-146f-47bd-90b0-51aea7b34ecd",
      "name": "Captura de tela 2024-02-19 112510.png",
      "key": "e7ad057a-6957-48ab-b6fa-8fbc480fbac0-Captura de tela 2024-02-19 112510.png"
    }
  ],
  "apportionments": [
    {
      "uid": "cc5b6f41-98fd-484d-b5be-0f3cd54646a1",
      "costCenter": "3.1.1.2.08.1 CUSTO MERCADORIAS IMPORTADAS",
      "accountingAccount": "3.1.2.1.01.3.00850-8 RESULTADO VARIACOES CAMBIAIS",
      "value": "100"
    }
  ]
}


