@HOST = http://localhost:8080/api

PATCH {{HOST}}/categories/76393821-114b-405f-ba12-8fc7f683a705/disable HTTP/1.1
Content-Type: application/json

# Campos obrigatórios: todos

{
    "enable": false
}

