@HOST = http://localhost:8080/api

POST {{HOST}}/auth/signup HTTP/1.1
Content-Type: application/json

# Campos obrigatórios: name, email, password, phone
# Opcional: document

{
  "name": "Eduardo",
  "email": "eduardo.stoelben@growdev.com.br",
  "password": "123456",
  "phone": "55981625040"
}
