@HOST = http://localhost:8080/api

POST {{HOST}}/payment-request-general HTTP/1.1
Content-Type: application/json

# Campos obrigatórios: todos

{
  "supplier": "12345678",
  "description": "Solicito pagamento para um equipamento novo.",
  "sendReceipt": true,
  "totalRequestValue": "300",
  "dueDate": "2024-02-02T12:00:00.000Z"
}

