@HOST = http://localhost:8080/api

GET  {{HOST}}/budget-account/balance/2023/3.1.1.2.08.1 CUSTO MERCADORIAS IMPORTADAS/3.1.2.1.01.3.00850-8 RESULTADO VARIACOES CAMBIAIS/marco HTTP/1.1
Content-Type: application/json
