@HOST = http://localhost:8080/api

POST {{HOST}}/products HTTP/1.1
Content-Type: application/json

# Campos obrigatórios: code, name, category, enable

{
  "categoryId": "4e292f89-ef81-41f4-8be8-da44c0012f8b",
  "code": "67890", 
  "name": "Caneta",
  "enable": true
}



